//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        public int ID_Home { get; set; }
        public string Name { get; set; }
        public string Opisanie { get; set; }
        public byte[] Image_Home { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ID_Drain { get; set; }
        public Nullable<int> ID_Door { get; set; }
        public Nullable<int> ID_Solution { get; set; }
        public Nullable<int> ID_Roof { get; set; }
        public Nullable<int> ID_Basement { get; set; }
        public Nullable<int> ID_Window { get; set; }
        public Nullable<int> ID_Pavers { get; set; }
        public Nullable<int> ID_Steps { get; set; }
        public Nullable<int> ID_Facade { get; set; }
        public Nullable<int> ID_Railing { get; set; }
        public Nullable<int> ID_Balka { get; set; }
        public Nullable<int> ID_Terrace { get; set; }
        public Nullable<int> ID_Plaster { get; set; }
    
        public virtual Balki_House Balki_House { get; set; }
        public virtual Door_For_House Door_For_House { get; set; }
        public virtual Drain_For_Home Drain_For_Home { get; set; }
        public virtual House_Basement_Cokol_ House_Basement_Cokol_ { get; set; }
        public virtual House_Facade House_Facade { get; set; }
        public virtual House_Steps House_Steps { get; set; }
        public virtual House_Windows House_Windows { get; set; }
        public virtual Pavers_House Pavers_House { get; set; }
        public virtual Plaster_for_the_house Plaster_for_the_house { get; set; }
        public virtual Railing_For_Home Railing_For_Home { get; set; }
        public virtual Roof_of_the_house Roof_of_the_house { get; set; }
        public virtual Terrace_Home Terrace_Home { get; set; }
        public virtual Turnkey_solution_for_home Turnkey_solution_for_home { get; set; }
    }
}
